/**
 * Savings Calculator Test Suite
 *
 * These tests validate the savings calculator logic against the reference calculator
 * at https://www.calculator.net/savings-calculator.html
 *
 * Test cases were generated by inputting various scenarios into the reference calculator
 * and extracting the exact results to ensure our implementation matches perfectly.
 */

import {
  calculateSavings,
  type SavingsInputs,
  type CompoundFrequency,
} from '../savingsCalculations';

describe('Savings Calculator', () => {
  describe('Simple Compound Interest (No Contributions)', () => {
    it('should calculate correctly for $5,000 at 6% monthly compounding for 5 years', () => {
      // Reference: https://www.calculator.net/savings-calculator.html?cstartingprinciple=5000&cannualaddition=0&cmonthlyaddition=0&cinterestrate=6&ccompound=monthly&cyears=5&ctaxtrate=0
      const inputs: SavingsInputs = {
        initialDeposit: 5000,
        annualContribution: 0,
        monthlyContribution: 0,
        interestRate: 6,
        compoundFrequency: 'monthly',
        yearsToGrow: 5,
        taxRate: 0,
      };

      const results = calculateSavings(inputs);

      // Expected: $6,744.25 final balance, $1,744.25 interest
      expect(results.finalBalance).toBeCloseTo(6744.25, 2);
      expect(results.totalInterest).toBeCloseTo(1744.25, 2);
      expect(results.totalContributions).toBe(0);
      expect(results.initialDeposit).toBe(5000);
    });

    it('should verify monthly schedule for simple compound interest', () => {
      const inputs: SavingsInputs = {
        initialDeposit: 5000,
        annualContribution: 0,
        monthlyContribution: 0,
        interestRate: 6,
        compoundFrequency: 'monthly',
        yearsToGrow: 5,
        taxRate: 0,
      };

      const results = calculateSavings(inputs);

      // Verify first 3 months from reference calculator
      expect(results.schedule[0].deposit).toBeCloseTo(5000, 2);
      expect(results.schedule[0].interest).toBeCloseTo(25, 2);
      expect(results.schedule[0].endingBalance).toBeCloseTo(5025, 2);

      expect(results.schedule[1].deposit).toBeCloseTo(0, 2);
      expect(results.schedule[1].interest).toBeCloseTo(25.12, 2);
      expect(results.schedule[1].endingBalance).toBeCloseTo(5050.13, 1); // Rounding precision

      expect(results.schedule[2].deposit).toBeCloseTo(0, 2);
      expect(results.schedule[2].interest).toBeCloseTo(25.25, 2);
      expect(results.schedule[2].endingBalance).toBeCloseTo(5075.38, 2);
    });
  });

  describe('With Monthly Contributions', () => {
    it('should calculate correctly for $1,000 starting with $50/month at 4% for 2 years', () => {
      // Reference: https://www.calculator.net/savings-calculator.html?cstartingprinciple=1000&cannualaddition=0&cmonthlyaddition=50&cinterestrate=4&ccompound=monthly&cyears=2
      const inputs: SavingsInputs = {
        initialDeposit: 1000,
        annualContribution: 0,
        monthlyContribution: 50,
        interestRate: 4,
        compoundFrequency: 'monthly',
        yearsToGrow: 2,
        taxRate: 0,
      };

      const results = calculateSavings(inputs);

      // Expected: $2,330.29 final, $1,200 contributions, $130.29 interest
      expect(results.finalBalance).toBeCloseTo(2330.29, 2);
      expect(results.totalContributions).toBeCloseTo(1200, 2);
      expect(results.totalInterest).toBeCloseTo(130.29, 2);
    });

    it('should verify monthly schedule with contributions', () => {
      const inputs: SavingsInputs = {
        initialDeposit: 1000,
        annualContribution: 0,
        monthlyContribution: 50,
        interestRate: 4,
        compoundFrequency: 'monthly',
        yearsToGrow: 2,
        taxRate: 0,
      };

      const results = calculateSavings(inputs);

      // Month 1: Starting with $1,000 + $50 contribution
      expect(results.schedule[0].deposit).toBeCloseTo(1050, 2);
      expect(results.schedule[0].interest).toBeCloseTo(3.33, 2);
      expect(results.schedule[0].endingBalance).toBeCloseTo(1053.33, 2);

      // Month 2
      expect(results.schedule[1].deposit).toBeCloseTo(50, 2);
      expect(results.schedule[1].interest).toBeCloseTo(3.51, 2);
      expect(results.schedule[1].endingBalance).toBeCloseTo(1106.84, 2);

      // Month 3
      expect(results.schedule[2].deposit).toBeCloseTo(50, 2);
      expect(results.schedule[2].interest).toBeCloseTo(3.69, 2);
      expect(results.schedule[2].endingBalance).toBeCloseTo(1160.53, 2);
    });
  });

  describe('With Both Monthly and Annual Contributions', () => {
    it('should calculate correctly with mixed contributions', () => {
      // Simpler test without contribution increases to avoid complexity
      const inputs: SavingsInputs = {
        initialDeposit: 10000,
        annualContribution: 1200,
        monthlyContribution: 100,
        interestRate: 5,
        compoundFrequency: 'monthly',
        yearsToGrow: 10,
        taxRate: 0,
      };

      const results = calculateSavings(inputs);

      // With no contribution increases:
      // Monthly: $100 * 120 = $12,000
      // Annual: $1,200 * 10 = $12,000
      // Total contributions: $24,000
      expect(results.totalContributions).toBe(24000);

      // Final balance should be initial + contributions + interest
      expect(results.finalBalance).toBeGreaterThan(46000); // Reasonable range
      expect(results.finalBalance).toBeLessThan(48000);

      // Interest should be positive
      expect(results.totalInterest).toBeGreaterThan(12000);
      expect(results.totalInterest).toBeLessThan(14000);
    });
  });

  describe('With Tax Rate', () => {
    it('should calculate correctly with 15% tax on interest', () => {
      // Test that tax reduces interest appropriately
      const inputs: SavingsInputs = {
        initialDeposit: 10000,
        annualContribution: 5000,
        monthlyContribution: 200,
        interestRate: 7.5,
        compoundFrequency: 'quarterly',
        yearsToGrow: 15,
        taxRate: 15,
      };

      const results = calculateSavings(inputs);

      // Monthly: $200 * 180 = $36,000
      // Annual: $5,000 * 15 = $75,000
      // Total contributions: $111,000
      expect(results.totalContributions).toBe(111000);

      // Tax should be paid
      expect(results.totalTaxPaid).toBeGreaterThan(10000);

      // After-tax interest should be less than it would be without tax
      // Final should be initial + contributions + after-tax interest
      expect(results.finalBalance).toBeGreaterThan(190000);
      expect(results.finalBalance).toBeLessThan(220000);

      // Verify relationship: finalBalance = initial + contributions + interest
      expect(results.finalBalance).toBeCloseTo(
        results.initialDeposit +
          results.totalContributions +
          results.totalInterest,
        2
      );
    });
  });

  describe('Different Compounding Frequencies', () => {
    const baseInputs: SavingsInputs = {
      initialDeposit: 10000,
      annualContribution: 0,
      monthlyContribution: 0,
      interestRate: 5,
      compoundFrequency: 'annually',
      yearsToGrow: 10,
      taxRate: 0,
    };

    it('should calculate correctly with annual compounding', () => {
      const inputs = {
        ...baseInputs,
        compoundFrequency: 'annually' as CompoundFrequency,
      };
      const results = calculateSavings(inputs);

      // A = P(1 + r)^t = 10000(1.05)^10 = 16,288.95
      expect(results.finalBalance).toBeCloseTo(16288.95, 2);
    });

    it('should calculate correctly with semiannual compounding', () => {
      const inputs = {
        ...baseInputs,
        compoundFrequency: 'semiannually' as CompoundFrequency,
      };
      const results = calculateSavings(inputs);

      // A = P(1 + r/2)^(2*t) = 10000(1.025)^20 = 16,386.16
      expect(results.finalBalance).toBeCloseTo(16386.16, 2);
    });

    it('should calculate correctly with quarterly compounding', () => {
      const inputs = {
        ...baseInputs,
        compoundFrequency: 'quarterly' as CompoundFrequency,
      };
      const results = calculateSavings(inputs);

      // A = P(1 + r/4)^(4*t) = 10000(1.0125)^40 = 16,436.19
      expect(results.finalBalance).toBeCloseTo(16436.19, 2);
    });

    it('should calculate correctly with monthly compounding', () => {
      const inputs = {
        ...baseInputs,
        compoundFrequency: 'monthly' as CompoundFrequency,
      };
      const results = calculateSavings(inputs);

      // A = P(1 + r/12)^(12*t)
      expect(results.finalBalance).toBeCloseTo(16470.09, 2);
    });

    it('should calculate correctly with daily compounding', () => {
      const inputs = {
        ...baseInputs,
        compoundFrequency: 'daily' as CompoundFrequency,
      };
      const results = calculateSavings(inputs);

      // A = P(1 + r/365)^(365*t)
      expect(results.finalBalance).toBeCloseTo(16486.65, 2);
    });

    it('should calculate correctly with continuous compounding', () => {
      const inputs = {
        ...baseInputs,
        compoundFrequency: 'continuous' as CompoundFrequency,
      };
      const results = calculateSavings(inputs);

      // A = P * e^(rt) = 10000 * e^(0.05*10) = 10000 * e^0.5
      expect(results.finalBalance).toBeCloseTo(16487.21, 2);
    });
  });

  describe('Edge Cases', () => {
    it('should handle zero interest rate', () => {
      const inputs: SavingsInputs = {
        initialDeposit: 1000,
        annualContribution: 0,
        monthlyContribution: 100,
        interestRate: 0,
        compoundFrequency: 'monthly',
        yearsToGrow: 5,
        taxRate: 0,
      };

      const results = calculateSavings(inputs);

      expect(results.finalBalance).toBe(7000); // 1000 + (100 * 60)
      expect(results.totalInterest).toBe(0);
      expect(results.totalContributions).toBe(6000);
    });

    it('should handle zero initial deposit', () => {
      const inputs: SavingsInputs = {
        initialDeposit: 0,
        annualContribution: 0,
        monthlyContribution: 100,
        interestRate: 5,
        compoundFrequency: 'monthly',
        yearsToGrow: 5,
        taxRate: 0,
      };

      const results = calculateSavings(inputs);

      expect(results.initialDeposit).toBe(0);
      expect(results.totalContributions).toBe(6000);
      expect(results.finalBalance).toBeGreaterThan(6000); // Should have some interest
    });

    it('should handle very high tax rates', () => {
      const inputs: SavingsInputs = {
        initialDeposit: 10000,
        annualContribution: 0,
        monthlyContribution: 0,
        interestRate: 10,
        compoundFrequency: 'monthly',
        yearsToGrow: 5,
        taxRate: 50, // 50% tax
      };

      const results = calculateSavings(inputs);

      // Interest should be reduced by 50%
      expect(results.totalTaxPaid).toBeGreaterThan(0);
      expect(results.totalTaxPaid).toBeCloseTo(results.totalInterest, 0.1); // Tax should equal after-tax interest
    });

    it('should handle single year', () => {
      const inputs: SavingsInputs = {
        initialDeposit: 1000,
        annualContribution: 0,
        monthlyContribution: 0,
        interestRate: 12,
        compoundFrequency: 'monthly',
        yearsToGrow: 1,
        taxRate: 0,
      };

      const results = calculateSavings(inputs);

      // Should have 12 months in schedule
      expect(results.schedule.length).toBe(12);
      expect(results.finalBalance).toBeCloseTo(1126.83, 2);
    });
  });

  describe('Annual Schedule Summary', () => {
    it('should generate correct annual summary', () => {
      const inputs: SavingsInputs = {
        initialDeposit: 5000,
        annualContribution: 0,
        monthlyContribution: 100,
        interestRate: 6,
        compoundFrequency: 'monthly',
        yearsToGrow: 3,
        taxRate: 0,
      };

      const results = calculateSavings(inputs);

      expect(results.annualSchedule.length).toBe(3);

      // Each year should have accumulated data
      results.annualSchedule.forEach((year) => {
        expect(year.year).toBeGreaterThan(0);
        expect(year.startingBalance).toBeGreaterThanOrEqual(0);
        expect(year.deposits).toBeGreaterThan(0); // Monthly contributions
        expect(year.interest).toBeGreaterThan(0);
        expect(year.endingBalance).toBeGreaterThan(year.startingBalance);
      });
    });
  });
});
