#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Load nvm and use the correct Node version
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Use Node version from .nvmrc if it exists
if [ -f .nvmrc ]; then
  nvm use
fi

npx lint-staged
